const constants: { [key: string]: string[] } = {
  stageText: ["階段", "阶段", "Stage", "Étape"],
  manual: ["自擬題目", "自拟题目", "Personal Task", "Tâche personnelle"],
  formaulaPlaceholder: [
    "輸入算式",
    "输入算式",
    "Enter formula",
    "Entrez la formule",
  ],
  topics: [
    "四則混合計算",
    "四则混合计算",
    "Four Mixed Operations",
    "Quatre Opérations Mixtes",
  ],
  resultBeValidHint: [
    "這計算結果不是一個正整數。",
    "这计算结果不是一个正整数。",
    "The result of this calculation is not a positive integer.",
    "Le résultat de ce calcul n'est pas un entier positif.",
    "這計算結果是一個循環小數或負數。",
    "这计算结果是一个循环小数或负数。",
    "The result of this calculation is a circulating decimal or a negative number.",
    "Le résultat de ce calcul est un nombre décimal en circulation ou un nombre négatif.",
  ],
  wellDone: [
    "你做得到﹗你完成了這題混合計算﹗",
    "你做得到﹗你完成了这题混合计算﹗",
    "You can do it! You have completed this mixed calculation!",
    "Vous pouvez le faire! Vous avez terminé ce calcul mixte!",
  ],
  numberOfOperatorsHintLeft: [
    "最少一步計算，最多",
    "最少一步计算，最多",
    "Minimum 1 operator, maximum ",
    "Minimum 1 opérateur, maximum ",
  ],
  numberOfOperatorsHintRight: [
    "步計算。",
    "步计算。",
    " operators.",
    " opérateurs.",
  ],
  multiplyDivideFirstHintLeft: [
    "首先計算",
    "首先计算",
    "Calculate ",
    "Calculez ",
  ],
  multiplyDivideFirstHintRight: [
    "，因為乘法或除法應在加法或減法之前計算。",
    "，因为乘法或除法应在加法或减法之前计算。",
    " first because multiplication or division should be calculated before addition or subtraction.",
    " d'abord parce que la multiplication ou la division doit être calculée avant l'addition ou la soustraction.",
  ],
  exchangeToAvoidNegativeHint: [
    "避免那減法得到一個負數。",
    "避免那减法得到一个负数。",
    " to avoid the subtraction getting a negative number.",
    " pour éviter que la soustraction n'obtienne un nombre négatif.",
  ],
  exchangeToAvoidDecimalHint: [
    "避免那除法得到一個小數。",
    "避免那除法得到一个小数。",
    " to avoid the division getting a decimal number.",
    " pour éviter que la division n'obtienne un nombre décimal.",
    "避免那除法得到一個循環小數。",
    "避免那除法得到一个循环小数。",
    " to avoid the division getting a circulating decimal.",
    " pour éviter que la division ne reçoive une décimale en circulation.",
  ],
  orText: ["或", "或", " or ", " ou "],
  calculateFirstHintLeft: [
    "首先計算",
    "首先计算",
    "Calculate ",
    "Calculez d'abord ",
  ],
  calculateFirstHintRight: ["。", "。", " first.", "."],
  subtractGetTensHint: [
    "因為這減法可以得到整十或整百，這使下一步計算變得更容易。",
    "因为这减法可以得到整十或整百，这使下一步计算变得更容易。",
    " because this subtraction can get the whole tens or the whole hundreds, it makes the next calculation easier.",
    " parce que cette soustraction peut obtenir les dizaines entières ou les centaines entières, elle facilite le calcul suivant.",
  ],
  divideGetSmallerHint: [
    "因為這除法可以得到一個較小的數，這使下一步計算變得更容易。",
    "因为这除法可以得到一个较小的数，这使下一步计算变得更容易。",
    " because this division can get a smaller number, which makes the next calculation easier.",
    " parce que cette division peut obtenir un nombre plus petit, ce qui facilite le prochain calcul.",
  ],
  rearrangeHintLeft: [
    "重新排列算式以便先計算",
    "重新排列算式以便先计算",
    "Rearrange the formula to calculate ",
    "Réorganiser la formule pour calculer d'abord ",
  ],
  rearrangeHintRight: ["，", "，", " first ", " "],
};

export default constants;
